version: '3'

services:
  db:
    image: postgres:12.3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db

volumes:
  postgres_data:
